name: Auto-Update & Merge PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
  push:
    branches:
      - contribution-*

jobs:
  update-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git commit -m "changes" || true

      - name: Merge master into PR branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
          git merge upstream/master --no-edit || true

    # test
      - name: Push result to PR branch
        run: |
          git push || true