name: PR Build

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
  push:
    branches:
      - contribution-*
      - master

# concurrency
concurrency:
  group: ${{ github.workflow }}-PR-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  update-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git merge origin/master --no-edit || true
          git commit -m "changes" || true

    # test
      - name: Push result to PR branch
        run: |
          git push || true

  build:
    if: ${{ github.event.pull_request.draft == false }}
    name: Build
    needs: update-pr
    uses: ./.github/workflows/_build-template.yml
    with:
      build-only: true
      namespace: "pr"
      image-id: "pr-${{ github.event.pull_request.number }}"
    secrets: inherit