name: Auto‑Update PR (union)

on:
  pull_request_target:
    branches:
      - master 
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

concurrency:
  group: ${{ github.workflow }}-PR-${{ github.event.number }}
  cancel-in-progress: true
  

jobs:
  update-pr:
    if: ${{ startsWith(github.event.pull_request.base.ref, 'contribution-') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # unione di master → branch della PR
      - name: Merge master into PR
        run: |
          git fetch origin master
          git merge origin/master --no-edit

      - name: Push result
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}

  build:
    if: ${{ github.event.pull_request.draft == false && startsWith(github.event.pull_request.base.ref, 'contribution-') }}
    name: Build
    needs: update-pr
    uses: ./.github/workflows/_build-template.yml
    with:
      build-only: true
      namespace: "pr"
      image-id: "pr-${{ github.event.pull_request.number }}"
    secrets: inherit