name: Auto-Update & Merge PRs

on:
    pull_request_target:
      types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
        - converted_to_draft
    push:
      branches:
        - 'contribution-**'

jobs:
  update-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        git fetch origin master
        git merge origin/master --no-edit || true
    - run: |
        git push origin HEAD:${{ github.event.pull_request.head.ref }} 