name: Build Frontend

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    uses: ./.github/workflows/_build-template.yml
    with:
      namespace: ${{ github.ref_name }}
      build-only: false 