name: Auto-Update & Merge PRs

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE_METHOD: rebase
          MERGE_METHOD: merge
